# Avoid useless messages
comment: off

coverage:
  status:
    project:
      default:
        # Commits pushed to master should not decrease
        # the overall project coverage by more than 1%
        target: auto
        threshold: 1%
    patch:
      default:
        # Be tolerant on small code coverage difference on
        # pull requests to limit noisy red coverage status
        target: auto
        threshold: 1%
