name: Bug report
description: Create a report to help us reproduce and correct the bug.
title: "[BUG]"
labels: bug
assignees: alfaro96

body:
  - type: markdown
    attributes:
      value: #### Before submitting a bug, please make sure the issue has not been already addressed by searching through the past issues.

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.

  - type: textarea
    attributes:
      label: Code to reproduce the problem
      description: Add a minimal example that we can reproduce the error by running the code.
      placeholder: Sample code to reproduce the problem.

  - type: textarea
    attributes:
      label: Expected behaviour
      description: Paste or describe the expected behaviour.
      placeholder: No error is thrown.

  - type: textarea
    attributes:
      label: Actual behaviour
      description: Paste or describe the behaviour you observe instead of the expected behaviour.
      placeholder: Paste or describe the actual output or traceback.

  - type: textarea
    attributes:
      label: Specifications
      description: Print the system information for debugging.

  - type: markdown
    attributes:
      value: Thanks for contributing!
