# Encourage contributors to use issue templates
blank_issues_enabled: false

# Direct people to external sites to receive certain reports
contact_links:
  - name: Discussions
    url: https://github.com/alfaro96/scikit-lr/discussions/new
    about: Ask questions and discuss with other scikit-lr community members.
