# Define an issue form to report a documentation improvement

name: Documentation improvement
description: Create a report to help us improve the documentation.
title: "[DOC]"
labels: documentation
assignees: alfaro96

body:
  - type: markdown
    attributes:
      value: |
        #### You can just open a pull request with the suggested change.

  - type: textarea
    attributes:
      label: Describe the issue linked to the documentation
      description: Tell us about the confusion introduced in the documentation.

  - type: textarea
    attributes:
      label: Suggest a potential alternative
      description: Tell us how we could improve the documentation in this regard.
