# Define an issue form to suggest a new algorithm or enhancement

name: Feature request
description: Suggest a new algorithm, enhancement to an existing algorithm, etc.
title: "[FEA]"
labels: feature
assignees: alfaro96

body:
  - type: markdown
    attributes:
      value: |
        #### If you want to propose a new algorithm, be sure that the inclusion criteria are met.

  - type: textarea
    attributes:
      label: Describe the workflow you want to enable

  - type: textarea
    attributes:
      label: Describe your proposed solution

  - type: textarea
    attributes:
      label: Describe alternatives you have considered

  - type: textarea
    attributes:
      label: Additional context
