version: "3"

services:
  sut:
    build:
      dockerfile: $DOCKERFILE_PATH
      context: .
      args:
        # Provide the commit hash to install the library from source
        SOURCE_COMMIT: $SOURCE_COMMIT

    # Get the laboratory version to test the image
    command: jupyter lab --version
