# Configuration file with base models

- config: base
  description: Base object for all models
  operations:
    evaluate:
      description: Evaluate metrics and record fit and score times
      main: evaluate
