# Configuration file for base models

- config: base
  description: Base object for all models
  operations:
    #
    evaluate:
      #
      flags:
        # 
        estimator_type:
          description: The string identifier of the estimator type
          type: string
          required: true
          choices: [label ranker, partial label ranker]
        #
        data_id:
          description: The identifier of the dataset
          type: int
          required: true
        #
        n_splits:
          description: The number of folds
          type: int
          default: 10
        #
        n_repeats:
          description: The number of times cross-validator needs to be repeated
          type: int
          default: 5
        #
        random_state:
          description: Controls the randomness of each repeated cross-validation instance
          type: int
          required: true
        #
        n_jobs:
          description: The number of jobs to run in parallel
          type: int
          default: 1
        #
        verbose:
          description: The verbosity level
          type: int
          default: 0
