name: Daily wheels tests

# Triggered every day to anticipate future errors
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  # Linux environment to build and test scikit-lr against
  # NumPy, SciPy and Cython installed from their CI wheels
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v1

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: source $GITHUB_WORKSPACE/.github/tools/cron/install.sh

      - name: Execute code tests
        run: bash $GITHUB_WORKSPACE/.github/tools/cron/test_script.sh

      - name: Execute documentation tests
        run: bash $GITHUB_WORKSPACE/.github/tools/cron/test_docs.sh

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          yml: ./.codecov.yml
          fail_ci_if_error: true
