name: Nightly tests

on:
  schedule:
    # Nightly test at 3:42 A.M.
    - cron: "42 3 */1 * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout scikit-lr
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: source $GITHUB_WORKSPACE/.github/tools/cron/install.sh

      - name: Execute code tests
        run: bash $GITHUB_WORKSPACE/.github/tools/cron/test_script.sh

      - name: Execute documentation tests
        run: bash $GITHUB_WORKSPACE/.github/tools/cron/test_docs.sh

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
