name: CRON tests

# This workflow is triggered every
# day only on the master branch
# on:
  # schedule:
    # - cron: "0 0 * * *"

# Just for testing, let us execute
# this workflow on pull request
on: pull_request

# Specify the build matrix
jobs:
  # Linux environment to build and test
  # scikit-lr against NumPy and SciPy
  # installed from their CI wheels
  build:
    # Use the latest Ubuntu version
    runs-on: ubuntu-latest
    # Execute the following steps in the workflow
    steps:
      # Cache dependencies to speed-up the build process
      - name: Cache modules
        uses: actions/cache@v1
        with:
          path: $HOME/.cache/pip
          key: ${{ runner.os }}-pip-{{hashFiles("**/requirements.txt")}}
          restore-keys: ${{ runner.os }}-pip-

      # Setup the Python 3.8 version
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # Checkout the master branch
      - name: Checkout master branch
        uses: actions/checkout@master

      # Install the dependencies
      - name: Install dependencies
        run: source .github/tools/scheduled/install.sh

      # Execute the tests
      - name: Execute tests
        run: bash .github/tools/scheduled/tests.sh

      # Upload the code coverage
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          yml: ./codecov.yml
          fail_ci_if_error: true
