name: Continuous deployment wheels

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python:
          - 36
          - 37
          - 38

    steps:
      - name: Checkout scikit-lr
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: source $GITHUB_WORKSPACE/.github/tools/deployment/install.sh

      - name: Build wheels
        run: bash $GITHUB_WORKSPACE/.github/tools/deployment/build_wheels.sh
        env: 
          CIBW_BUILD: cp${{ matrix.python }}-*
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest --showlocals --durations=20 --pyargs sklr

      - name: Upload wheels
        env:
          CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
        # The wheels should not be uploaded on PRs
        if: ${{ github.event_name != 'pull_request' }}
        run: bash upload_wheels.sh
