name: Continuous deployment wheels

on: pull_request
  # schedule:
  #   - cron: "0 0 * * *"
  # tags:
  #   - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python:
          - 3.6
          - 3.7
          - 3.8
    
    env:
      NUMPY_VERSION: 1.17.3
      SCIPY_VERSION: 1.3.2
      CYTHON_VERSION: 0.29.14
      MB_PYTHON_VERSION: ${{ matrix.python }}

    steps:
      - name: Checkout scikit-lr
        uses: actions/checkout@v2
        with:
          path: scikit-lr
      
      - name: Checkout multibuild
        uses: actions/checkout@v2
        with:
          repository: matthew-brett/multibuild
          path: multibuild

      - name: Copy configuration
        run: |
          ls -al
          ls -al $GITHUB_WORKSPACE
          cp $GITHUB_WORKSPACE/scikit-lr/.github/tools/deployment/config.sh $GITHUB_WORKSPACE
          ls -al
          ls -al $GITHUB_WORKSPACE
