name: Continuous integration tests

# Triggered on each push or PR only for the master
# and release branches because feature and bug-fix
# branches are merged via PR
on:
  push:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"

jobs:
  # Linux and macOS environments to test that scikit-lr can be built
  # against the minimum required versions of NumPy, SciPy and Cython
  integration:
    runs-on: ${{ matrix.os }}

    strategy:
      # Build matrix with operating systems and
      # Python versions supported by scikit-lr
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python: ["3.6", "3.7", "3.8"]

    # Minimum required version of NumPy, SciPy
    # and Cython to build scikit-lr from source
    env:
        NUMPY_VERSION: 1.17.3
        SCIPY_VERSION: 1.3.2
        CYTHON_VERSION: 0.29.14

    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: source $GITHUB_WORKSPACE/.github/tools/integration/install.sh

      - name: Execute code tests
        run: bash $GITHUB_WORKSPACE/.github/tools/integration/test_script.sh

      - name: Execute documentation tests
        run: bash $GITHUB_WORKSPACE/.github/tools/integration/test_docs.sh

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          yml: ./.codecov.yml
          fail_ci_if_error: true
