# Workflow to continuous test the library and documentation
name: Continuous integration tests

on:
  push:
    branches:
      - master
      # Release branches
      - "[0-9]+.[0-9]+.X"
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"

jobs:
  test:
    name: Continuous test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.6, 3.7, 3.8]

    env:
        NUMPY_MIN_VERSION: 1.14.6
        SCIPY_MIN_VERSION: 1.1.0
        CYTHON_MIN_VERSION: 0.28.5
        PYTEST_MIN_VERSION: 5.0.1
        PYTEST_COV_MIN_VERSION: 2.9.0
        SCIKIT_LEARN_MIN_VERSION: 0.24.0

    steps:
      - name: Checkout scikit-lr
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: source $GITHUB_WORKSPACE/.github/tools/integration/install.sh

      - name: Test library
        run: bash $GITHUB_WORKSPACE/.github/tools/integration/test_script.sh

      - name: Test documentation
        run: bash $GITHUB_WORKSPACE/.github/tools/integration/test_docs.sh

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
