name: Continuous integration tests

# Triggered on each push and PR for the master and release branches
# because feature and bug-fix branches will be merged via these PRs
on:
  push:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      # Build and test using the minimum required versions
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python:
          - 3.6
          - 3.7
          - 3.8

    env:
        NUMPY_VERSION: 1.17.3
        SCIPY_VERSION: 1.3.2
        CYTHON_VERSION: 0.29.14
        SCIKIT_LEARN_VERSION: 0.22.0

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: source $GITHUB_WORKSPACE/.github/tools/integration/install.sh

      - name: Execute code tests
        run: bash $GITHUB_WORKSPACE/.github/tools/integration/test_script.sh

      - name: Execute documentation tests
        run: bash $GITHUB_WORKSPACE/.github/tools/integration/test_docs.sh

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
