name: Linting tests

# This workflow will be triggered on each push or pull request
# but only for the master and release branches, since feature
# and bug-fix branches will be merged via pull request. Thus,
# it ensures that changes are integrated without any issue
on:
  push:
    branches:
      - master
      - [0-9]+.[0-9]+.X
  pull_request:
    branches:
      - master
      - [0-9]+.[0-9]+.X

jobs:
  # Linux environment to test that PRs do not add
  # obvious flake8 violations. It relies on two things:
  #   - Find common ancestor between branch
  #     and scikit-lr/scikit-lr remote.
  #   - run flake8 --diff on the diff between
  #     the branch and the common ancestor.
  linting:
    # Use the latest Ubuntu version
    runs-on: ubuntu-latest
    # Execute the following steps in the workflow
    steps:
      # Checkout the branch that issue the workflow
      - name: Checkout branch
        uses: actions/checkout@v1

      # Setup the Python 3.8 version
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # Install the dependencies
      - name: Install dependencies
        run: source $GITHUB_WORKSPACE/.github/tools/linting/install.sh

      # Test the linting
      - name: Test linting
        run: bash $GITHUB_WORKSPACE/.github/tools/linting/test.sh
