name: Linting tests

# Triggered on each push or PR only for the master
# and release branches because feature and bug-fix
# branches are merged via PR
on:
  push:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"

jobs:
  # Linux environment to assert that PRs
  # do not add obvious flake8 violations
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: source $GITHUB_WORKSPACE/.github/tools/linting/install.sh

      - name: Test linting
        run: bash $GITHUB_WORKSPACE/.github/tools/linting/test.sh
