# Workflow to check linting violations
name: Linting check

on:
  push:
    branches:
      - master
      # Release branches
      - "[0-9]+.[0-9]+.X"
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"

jobs:
  check:
    name: Check linting violations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout scikit-lr
        uses: actions/checkout@v2
        with:
          # Checkout pull request head commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: bash $GITHUB_WORKSPACE/.github/tools/linting/install.sh

      - name: Check linting
        run: bash $GITHUB_WORKSPACE/.github/tools/linting/check.sh
