name: Linting tests

# Triggered on each push and PR for the master and release branches
# because feature and bug-fix branches will be merged via these PRs
on:
  push:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"

jobs:
  test:
    # Linux environment to assert that PRs
    # do not add obvious flake8 violations
    runs-on: ubuntu-latest

    steps:
      # Use the first version to checkout because in the second
      # version, the workflow payload contains a wrong revision
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: source $GITHUB_WORKSPACE/.github/tools/linting/install.sh

      - name: Test linting
        run: bash $GITHUB_WORKSPACE/.github/tools/linting/test.sh
